version: "3.9"

services:
  glutz-eaccessserver:
    build: .
    restart: unless-stopped
    ports:
      - 26682:26682
    volumes:
      - ./db:/db
      - ./workspace:/workspace
    env_file:
      - .env